account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('logout/',
         auth_views.LogoutView.as_view(), name='logout'),
    path('login/',
         auth_views.LoginView.as_view(
             redirect_authenticated_user=True), name='login'),

    path('signup/customer/',
         views.CustomerSignUpView.as_view(), name='customer_signup'),
    path('customer/create-profile/',
         views.customer_create_profile, name='customer_create_profile'),
    path('customer/update-profile/',
         views.customer_update_profile, name='customer_update_profile'),
    path('customer/my-rentals/',
         views.customer_previous_rentals, name='customer_previous_rentals'),
    path('customer/verify/',
         views.customer_verification, name='customer_verification'),

    path('signup/carvendor/',
         views.VendorSignUpView.as_view(), name='vendor_signup'),
    path('vendor/create-profile/',
         views.vendor_create_profile, name='vendor_create_profile'),
    path('vendor/update-profile/',
         views.vendor_update_profile, name='vendor_update_profile'),
    path('vendor/my-vehicles/',
         views.vendor_manage_vehicles, name='vendor_manage_vehicles'),
     path('vendor/orders/',
         views.vendor_manage_orders, name='vendor_manage_orders'),
    path('vendor/<str:username>/',
         views.vendor_profile, name='vendor_profile'),
]

carrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('vehicles/', include('vehicle.urls', namespace='vehicle')),
    path('search/', search, name='search'),
    path('paystack/', include(('paystack.frameworks.django.urls', 'paystack'), namespace='paystack')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vehicle/urls.py
from django.urls import path

from . import views

app_name = 'vehicle'

urlpatterns = [
    path('create/', views.vehicle_create, name='create'),
    path('vendors/', views.vendor_list, name='vendors'),
    path('compare/', views.compare_vehicles, name='compare'),
    path('done/', views.payment_done, name='payment_done'),
    path('confirm-booking/',
         views.confirm_booking, name='confirm_booking'),
    path('add-to-compare/<int:pk>/',
         views.add_to_compare, name='add_to_compare'),
    path('<int:pk>/', views.vehicle_detail, name='detail'),
    path('<int:pk>/update/', views.vehicle_update, name='update'),
    path('<int:pk>/delete/', views.vehicle_delete, name='delete'),
    path('', views.vehicle_list, name='list'),

]

templates/customer/form.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}

{% block title %}{% if create %}Create{% else %}Update{% endif %} Profile{% endblock %} 

{% block content %} 

<section class="py-5 bg-dark">
    <div class="container">
        <div class="mb-5 text-white">
            <h1 class="fw-bolder">{% if create %}Create{% else %}Update{% endif %} Profile</h1>
            {% if create %}<p>Before you can start using this platform, you will need to create a Profile for your Account.</p>{% endif %}
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row">
          <div class="col-7 mx-auto">
            {% include 'partials/_alerts.html' %}
            <form class="row g-3" method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">{% if create %}Create{% else %}Update{% endif %}</button>
            </form>
          </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/customer/profile.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}Profile{% endblock %}

{% block content %}

<section class="py-5">
    <div class="container">
        <div class="row">
            <aside class="col-lg-3">
                {% include 'partials/_account_nav.html' %}
            </aside>
            <div class="col-lg-9">
                <div class="card mb-4">
                    <div class="card-body">
                        <header class="d-md-flex">
                            <div class="flex-shrink-0 circle rounded-circle text-center bg-primary">
                                <span
                                    class="initials position-relative lh-1">{{ request.user|make_list|first|title }}</span>
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5 class="m-0">{{ request.user.get_full_name|default:request.user.username|title }}
                                </h5>
                                <small>Registered {{ request.user.date_joined|naturalday }}</small>
                            </div>
                            <div>
                                <a href="{% url 'account:settings' %}" class="btn btn-sm btn-outline-primary">Edit
                                    Profile</a>
                            </div>
                        </header>
                    </div>
                </div>
                <h4 class="mb-4">My Materials Library</h4>
                <div class="row">
                    {% for material in materials %}
                    {% include 'partials/_material_item.html' %}
                    {% empty %}
                    <p class="text-center mt-5">No material in your library yet.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

templates/customer/rentals.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}Your Past Rentals{% endblock %}

{% block content %}

<section class="py-5 bg-dark">
    <div class="container px-5 my-5">
        <div class="mb-5 text-white">
            <h1 class="fw-bolder">Your Past Rentals</h1>
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container px-5 my-5">
        <div class="card">
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Vehicle Name</th>
                            <th>License Plate</th>
                            <th>Price</th>
                            <th>Days</th>
                            <th>Rent between</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for rent in rents %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>
                                <a href="{% url 'vehicle:detail' rent.vehicle.id %}">{{ rent.vehicle.name }}</a>
                                <br />
                                <small>Model: {{ rent.vehicle.model }}</small>
                            </td>
                            <td>{{ rent.vehicle.license_plate }}</td>
                            <td>&#8358;{{ rent.total_amount|intcomma }}</td>
                            <td>{{ rent.total_days }}</td>
                            <td>{{ rent.date_of_booking }} to {{ rent.date_of_return }}</td>
                        </tr>
                        {% empty %} You have not rented any vehicle yet.
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/customer/verify.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}

{% block title %}Verify your Phone number{% endblock %} 

{% block content %} 

<section class="py-5 bg-dark">
    <div class="container">
        <div class="mb-5 text-white">
            <h1 class="fw-bolder">Verify your Phone number</h1>
            <p>Before you can place an order for a car using this platform, you will need to verify your Phone number linked to your account.</p>
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row">
          <div class="col-5 mx-auto">
            {% include 'partials/_alerts.html' %}
            <form class="row g-3" method="post" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Verify</button>
            </form>
          </div>
        </div>
    </div>
</section>

{% endblock content %}