account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('logout/',
         auth_views.LogoutView.as_view(), name='logout'),
    path('login/',
         auth_views.LoginView.as_view(
             redirect_authenticated_user=True), name='login'),

    path('signup/customer/',
         views.CustomerSignUpView.as_view(), name='customer_signup'),
    path('customer/create-profile/',
         views.customer_create_profile, name='customer_create_profile'),
    path('customer/update-profile/',
         views.customer_update_profile, name='customer_update_profile'),
    path('customer/my-rentals/',
         views.customer_previous_rentals, name='customer_previous_rentals'),
    path('customer/verify/',
         views.customer_verification, name='customer_verification'),

    path('signup/carvendor/',
         views.VendorSignUpView.as_view(), name='vendor_signup'),
    path('vendor/create-profile/',
         views.vendor_create_profile, name='vendor_create_profile'),
    path('vendor/update-profile/',
         views.vendor_update_profile, name='vendor_update_profile'),
    path('vendor/my-vehicles/',
         views.vendor_manage_vehicles, name='vendor_manage_vehicles'),
     path('vendor/orders/',
         views.vendor_manage_orders, name='vendor_manage_orders'),
    path('vendor/<str:username>/',
         views.vendor_profile, name='vendor_profile'),
]

carrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('vehicles/', include('vehicle.urls', namespace='vehicle')),
    path('search/', search, name='search'),
    path('paystack/', include(('paystack.frameworks.django.urls', 'paystack'), namespace='paystack')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vehicle/urls.py
from django.urls import path

from . import views

app_name = 'vehicle'

urlpatterns = [
    path('create/', views.vehicle_create, name='create'),
    path('vendors/', views.vendor_list, name='vendors'),
    path('compare/', views.compare_vehicles, name='compare'),
    path('done/', views.payment_done, name='payment_done'),
    path('confirm-booking/',
         views.confirm_booking, name='confirm_booking'),
    path('add-to-compare/<int:pk>/',
         views.add_to_compare, name='add_to_compare'),
    path('<int:pk>/', views.vehicle_detail, name='detail'),
    path('<int:pk>/update/', views.vehicle_update, name='update'),
    path('<int:pk>/delete/', views.vehicle_delete, name='delete'),
    path('', views.vehicle_list, name='list'),

]

vehicle/models.py
from django.db import models
from django.conf import settings

from account.models import VendorProfile

User = settings.AUTH_USER_MODEL


class CarType(models.Model):
    name = models.CharField(max_length=20, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class GearType(models.Model):
    name = models.CharField(max_length=20, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class FuelType(models.Model):
    name = models.CharField(max_length=20, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Area(models.Model):
    city = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.city


class Vehicle(models.Model):
    vendor = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='vehicles')
    name = models.CharField(max_length=60)
    model = models.CharField(max_length=10, blank=True)
    color = models.CharField(max_length=20)
    no_of_seats = models.IntegerField()
    description = models.TextField(max_length=5000)
    car_type = models.ForeignKey(
        CarType, on_delete=models.PROTECT,
        blank=True, null=True)
    gear_type = models.ForeignKey(
        GearType, on_delete=models.PROTECT,
        blank=True, null=True)
    fuel_type = models.ForeignKey(
        FuelType, on_delete=models.PROTECT,
        blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='vehicle')
    is_available = models.BooleanField(default=True)
    license_plate = models.CharField(max_length=20, unique=True)
    area = models.ForeignKey(Area, on_delete=models.PROTECT)
    compares = models.ManyToManyField(
        User, related_name='compare', blank=True, default=None)
    # status: if car is available or not (out for rent)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.license_plate} : {self.name}"


class Rent(models.Model):
    PENDING = 'P'
    APPROVED = 'A'
    DECLINED = 'D'
    REQUEST_STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (DECLINED, 'Declined'),
    ]
    date_of_booking = models.DateField(blank=True, null=True)
    date_of_return = models.DateField(blank=True, null=True)
    advance_amount = models.IntegerField(blank=True, null=True) # remove
    total_amount = models.DecimalField(
        max_digits=12, decimal_places=2,
        blank=True, null=True)
    is_available = models.BooleanField(default=True)
    paid = models.BooleanField(default=False)
    request_status = models.CharField(
        max_length=1, choices=REQUEST_STATUS_CHOICES, default=PENDING) # remove
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='rents')
    vendor = models.ForeignKey(
        VendorProfile, on_delete=models.CASCADE, related_name='rents')
    paystack_id = models.CharField(max_length=150, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"Rent #{self.id}: {self.vehicle.name}"

    @property
    def total_days(self):
        date_of_booking = self.date_of_booking
        date_of_return = self.date_of_return
        if date_of_booking > date_of_return:
            return
        dates = (date_of_return - date_of_booking)
        return dates.days

    @property
    def get_cost(self):
        return self.vehicle.price

    @property
    def get_total_cost(self):
        return self.get_cost * self.total_days

vehicle/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
from django.utils.crypto import get_random_string
from django.urls import reverse
from django.conf import settings

from carrental.utils import mk_paginator
from account.models import VendorProfile
from .models import Vehicle, Rent
from .forms import VehicleForm, RentForm


def vendor_list(request):
    vendors = VendorProfile.objects.all()
    return render(
        request, 'vehicle/vendors.html',
        {'vendors': vendors})


def vehicle_list(request):
    vehicles = Vehicle.objects.filter(is_available=True)
    vehicles = mk_paginator(request, vehicles, 9)

    return render(
        request, 'vehicle/list.html', {'vehicles': vehicles})


def vehicle_detail(request, pk):
    vehicle = get_object_or_404(Vehicle, id=pk)
    recommended_vehicles = Vehicle.objects.exclude(id=vehicle.id).order_by('?')[:3]
    compared = bool
    if vehicle.compares.filter(id=request.user.id).exists():
        compared = True
    if request.method == 'POST':
        form = RentForm(request.POST)
        if form.is_valid():
            rent = form.save(commit=False)
            rent.customer = request.user
            rent.vehicle = vehicle
            rent.vendor = vehicle.vendor.vendor_profile
            rent.save()
            request.session['order_id'] = rent.id
            return redirect('vehicle:confirm_booking')
        else:
            messages.warning(
                request, "Your selected dates are incorrect. Try again")
    else:
        form = RentForm()

    return render(
        request, 'vehicle/detail.html', {'vehicle': vehicle,
                                         'recommended_vehicles': recommended_vehicles,
                                         'compared': compared,
                                         'form': form})


@login_required
def confirm_booking(request):
    rent_id = request.session.get('order_id')
    rent = get_object_or_404(Rent, id=rent_id)

    paystack_amount = int(rent.get_total_cost * 100)
    paystack_ref = None
    if not paystack_ref:
        paystack_ref = get_random_string(length=12).upper()
        rent.paystack_id = paystack_ref
        rent.total_amount = rent.get_total_cost
        rent.save()
    paystack_redirect_url = "{}?amount={}".format(
        reverse('paystack:verify_payment',
                args=[paystack_ref]), paystack_amount, rent)

    template = 'vehicle/confirm_booking.html'
    context = {'rent': rent,
                   'paystack_key': settings.PAYSTACK_PUBLIC_KEY,
                   'paystack_amount': paystack_amount,
                   'paystack_redirect_url': paystack_redirect_url
    }
    return render(request, template, context)


@csrf_exempt
def payment_done(request):
    rent_id = request.session.get('rent_id')
    rent = get_object_or_404(Rent, id=rent_id)
    return render(request, 'vehicle/invoice.html', {'rent': rent})


@csrf_exempt
def payment_canceled(request):
    return render(request, 'canceled.html')


@login_required
def rented_vehicles(request):
    vehicles = Rent.objects.filter(customer=request.user)

    return render(
        request, 'rented_vehicles.html', {'vehicles': vehicles})


@login_required
def add_to_compare(request, pk):
    vehicle = get_object_or_404(Vehicle, id=pk)
    if vehicle.compares.filter(id=request.user.id).exists():
        vehicle.compares.remove(request.user)
        messages.success(
            request, "You've removed the vehicle from comparison")
    else:
        vehicle.compares.add(request.user)
        messages.success(
            request, "You've added this vehicle for comparison")
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def compare_vehicles(request):
    vehicles = Vehicle.objects.filter(
        is_available=True).filter(compares=request.user)[:3]
    return render(
        request, 'vehicle/compare.html', {'vehicles': vehicles})


@login_required
def vehicle_create(request):
    if not request.user.is_vendor:
        messages.info(
            request, "Login as a vendor to upload vehicle.")
        logout(request)
        return redirect('login')
    if request.method == 'POST':
        form = VehicleForm(request.POST, request.FILES)
        if form.is_valid():
            vehicle = form.save(commit=False)
            vehicle.vendor = request.user
            vehicle.save()
            messages.success(
                request, "Vehicle data successfully uploaded.")
            return redirect('vehicle:detail', vehicle.id)
        else:
            messages.warning(
                request, "An error occured, please check below.")
    else:
        form = VehicleForm()

    return render(
        request, 'vehicle/form.html', {'form': form, 'create': True})


@login_required
def vehicle_update(request, pk):
    vehicle = get_object_or_404(Vehicle, id=pk, vendor=request.user)
    if request.method == 'POST':
        form = VehicleForm(request.POST, request.FILES, instance=vehicle)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Vehicle data successfully updated.")
            return redirect('vehicle:detail', vehicle.id)
        else:
            messages.warning(
                request, "An error occured, please check below.")
    else:
        form = VehicleForm(instance=vehicle)

    return render(request,
                  'vehicle/form.html',
                  {'form': form, 'create': False, 'vehicle': vehicle})


@login_required
def vehicle_delete(request, pk):
    vehicle = get_object_or_404(Vehicle, id=pk, vendor=request.user)
    if request.method == 'POST':
        vehicle.delete()
        messages.success(request, 'Vehicle successfully deleted')
        return redirect('vehicle_list')

    return render(request,
                  'vehicle/confirm_delete.html',
                  {'vehicle': vehicle})


# def check_availability(request, license_plate):
#     import datetime

#     date_of_booking = request.POST.get(
#         'date_of_booking', '')
#     date_of_return = request.POST.get(
#         'date_of_return', '')

#     date_of_booking = datetime.strptime(
#         date_of_booking, '%Y-%m-%d').date()
#     date_of_return = datetime.strptime(
#         date_of_return, '%Y-%m-%d').date()

#     rentvehicle = Rent.objects.filter(
#         license_plate=license_plate)
#     vehicle = Vehicle.objects.get(
#         license_plate=license_plate)

#     customer_email = request.session.get('user_email')
#     customer = Customer.objects.get(
#         customer_email=customer_email)

#     if date_of_booking < datetime.date.today():
#         Incorrect_dates = "Please give proper dates"
#         return render(
#             request, 'showdetails.html',
#             {'Incorrect_dates': Incorrect_dates,
#              'vehicle': vehicle, 'customer': customer})

#     if date_of_return < date_of_booking:
#         Incorrect_dates = "Please give proper dates"
#         return render(
#             request, 'showdetails_loggedin.html',
#             {'Incorrect_dates': Incorrect_dates,
#              'vehicle': vehicle, 'customer': customer})

#     days = (date_of_return - date_of_booking).days + 1
#     total = days * vehicle.price

#     rent_data = {
#         "date_of_booking": date_of_booking,
#         "date_of_return": date_of_return,
#         "days": days, "total": total
#     }

#     for rv in rentvehicle:
#         if (rv.date_of_booking >= date_of_booking and date_of_return >= rv.date_of_booking) or (date_of_booking >= rv.date_of_booking and date_of_return <= rv.date_of_return) or (date_of_booking <= rv.date_of_return and date_of_return >= rv.date_of_return):
#             if rv.isAvailable:
#                 Available = True
#                 Message = "Someone has requested for this vehicle from " + \
#                     str(rv.RentVehicle_Date_of_Booking) + \
#                     " to " + str(rv.RentVehicle_Date_of_Return)
#                 return render(
#                     request,
#                     'showdetails.html',
#                     {'Message': Message,
#                      'Available': Available,
#                      'vehicle': vehicle,
#                      'customer': customer,
#                      'rent_data': rent_data})

#             NotAvailable = True
#             return render(
#                 request,
#                 'showdetails.html',
#                 {'NotAvailable': NotAvailable,
#                  'dates': rv,
#                  'vehicle': vehicle,
#                  'customer': customer})

#         # if (RentVehicle_Date_of_Booking < rv.RentVehicle_Date_of_Booking and RentVehicle_Date_of_Return < rv.RentVehicle_Date_of_Booking) or (RentVehicle_Date_of_Booking > rv.RentVehicle_Date_of_Return and RentVehicle_Date_of_Return > rv.RentVehicle_Date_of_Return):
#         #     Available = True
#         #     return render(request,'showdetails_loggedin.html',{'Available':Available,'vehicle':vehicle,'customer':customer,'rent_data':rent_data})

#     Available = True

#     return render(
#         request, 'showdetails.html',
#         {'Available': Available, 'vehicle': vehicle,
#          'customer': customer, 'rent_data': rent_data})

templates/vehicle/compare.html
{% extends "base.html" %} 

{% block title %}Compare Vehicles{% endblock %}

{% block content %} 

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-12">
            {% include 'partials/_alerts.html' %}
            {% if vehicles %}
        	<div class="responsive-table">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Specifications</th>
                            {% for vehicle in vehicles %}
                            <td>
	                            <img src="{{ vehicle.image.url }}" style="width: 150px;" alt="{{ vehicle.name }}">
                                <h5><a href="{% url 'vehicle:detail' vehicle.id %}">{{ vehicle.name }}</a></h5>
                            </td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>Price (per day)</th>
                            {% for vehicle in vehicles %}
                            	<td>&#8358;{{ vehicle.price }}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>Color</th>
                            {% for vehicle in vehicles %}
                                <td>{{ vehicle.color }}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>Vendor</th>
                            {% for vehicle in vehicles %}
                                <td>{{ vehicle.vendor.vendor_profile.company_name }}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>No. of seats</th>
                            {% for vehicle in vehicles %}
                            	<td>{{ vehicle.no_of_seats }}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>Car Type</th>
                            {% for vehicle in vehicles %}
                            	<td>{{ vehicle.car_type }}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>Gear Type</th>
                            {% for vehicle in vehicles %}
                            	<td>{{ vehicle.gear_type }}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>Fuel Type</th>
                            {% for vehicle in vehicles %}
                            	<td>{{ vehicle.fuel_type }}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th></th>
                            {% for vehicle in vehicles %}
                            <td>
                                <a class="btn btn-warning" href="{% url 'vehicle:add_to_compare' vehicle.id %}">Remove from Compare</a>
                            </td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="text-center vh-100 mt-5">
                <h4>You have not added any Vehicle to your comparison table yet.</h4>
                <a href="{% url 'vehicle:list' %}">Browse Vehicles</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/vehicle/detail.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}

{% block title %}{{ vehicle.name }}{% endblock %}

{% block content %} 

<div class="container mt-5">
    <div class="row">
        <!-- <div class="col-lg-12">
            <div class="d-inline-block text-white bg-info p-2">2023</div>
            <div class="d-flex d-inline-block gap-1">
                <i class="fa-solid fa-star text-warning small lh-base"></i>
                <i class="fa-solid fa-star text-warning small lh-base"></i>
                <i class="fa-solid fa-star text-warning small lh-base"></i>
                <i class="fa-solid fa-star text-warning small lh-base"></i>
                <span class="lh-sm">4.0</span>
            </div>
            
        </div> -->
        <div class="col-lg-8">
            <article>
            	{% include 'partials/_alerts.html' %}
                <header class="mb-4">
                    <h1 class="fw-bolder mb-1">{{ vehicle.name }} {% if vehicle.model %}({{ vehicle.model }}){% endif %}</h1>
                    <div class="mb-2 d-flex justify-content-between">
                    	<h3>&#8358;{{ vehicle.price }} <small class="text-body-secondary">/ day</small></h3>
                    	<span>
                    		{% if request.user.is_authenticated %}
                                {% if compared %}
                                    <a class="btn btn-warning" href="{% url 'vehicle:add_to_compare' vehicle.id %}">Remove from Compare</a> 
                                {% else %}
                                    <a class="btn btn-success" href="{% url 'vehicle:add_to_compare' vehicle.id %}">Add to Compare</a>
                                {% endif %}
                                {% if request.user == vehicle.vendor %}
                    		    <a class="btn btn-primary" href="{% url 'vehicle:update' vehicle.id %}">Update Vehicle</a>
                                {% endif %}
                            {% endif %}
                    	</span>
                    </div>
                </header>
                <figure class="mb-4">
                    <img class="img-fluid rounded" src="{{ vehicle.image.url }}" alt="{{ vehicle.name }}" />
                </figure>
                <section class="mb-5">
                	<h4>Vehicle Description</h4>
                    <p class="fs-5 mb-4">{{ vehicle.description|linebreaks }}</p>
                </section>
            </article>
        </div>
        <div class="col-lg-4">
            
            {% if request.user.is_authenticated %}
                {% if not request.user.is_vendor and request.user.customer_profile.verified  %}
                <div class="card mb-4">
                    <div class="card-header">Book Now</div>
                    <div class="card-body">
                        <form method="post" action="">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" class="btn btn-success" value="Place booking" />
                        </form>
                    </div>
                </div>
                {% endif %}
            {% else %}
                <a href="{% url 'login' %}?next={% url 'vehicle:detail' vehicle.id %}" class="btn btn-success d-block mb-4">Login to Book Vehicle</a>
            {% endif %}
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4">
                            <h6 class="mb-0">Vendor</h6>
                        </div>
                        <div class="col-sm-8 text-secondary">
                            <a href="{% url 'vendor_profile' vehicle.vendor.vendor_profile.user.username %}">{{ vehicle.vendor.vendor_profile.company_name }}</a>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <h6 class="mb-0">Color</h6>
                        </div>
                        <div class="col-sm-8 text-secondary">
                            {{ vehicle.color }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <h6 class="mb-0">Location</h6>
                        </div>
                        <div class="col-sm-8 text-secondary">
                            {{ vehicle.area }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <h6 class="mb-0">Car Type</h6>
                        </div>
                        <div class="col-sm-8 text-secondary">
                            {{ vehicle.car_type }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <h6 class="mb-0">Fuel Type</h6>
                        </div>
                        <div class="col-sm-8 text-secondary">
                            {{ vehicle.fuel_type }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <h6 class="mb-0">Seats</h6>
                        </div>
                        <div class="col-sm-8 text-secondary">
                            {{ vehicle.no_of_seats }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <h6 class="mb-0">Gear Type</h6>
                        </div>
                        <div class="col-sm-8 text-secondary">
                             {{ vehicle.gear_type }} 
                        </div>
                    </div>
                </div>
            </div>            
        </div>
    </div>
    <div class="row gx-5 my-5">
        <h3 class="mb-5">Recommended Vehicles</h3>
        {% for vehicle in recommended_vehicles %}
        {% include 'partials/_car_listings.html' %}
        {% endfor %}
    </div>
</div>

{% endblock content %}

templates/vehicle/form.html
{% extends "base.html" %} 

{% block title %}{% if create %}Upload{% else %}Update{% endif %} Vehicle{% endblock %} 

{% block content %} 

<section class="py-5 bg-dark">
    <div class="container">
        <div class="mb-5 text-white">
            <h1 class="fw-bolder">{% if create %}Upload{% else %}Update{% endif %} Vehicle for Rental</h1>
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container px-5 my-5">
        {% include 'partials/_alerts.html' %}
        <form class="row g-3" method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
          <div class="col-md-4">
            <label for="id_name" class="form-label">Name</label>
            {{ form.name }}
          </div>
          <div class="col-md-4">
            <label for="id_model" class="form-label">Model</label>
            {{ form.model }}
          </div>
          <div class="col-md-4">
            <label for="id_license_plate" class="form-label">License Plate</label>
            {{ form.license_plate }}
          </div>
          <div class="col-3">
            <label for="id_color" class="form-label">Color</label>
            {{ form.color }}
          </div>
          <div class="col-3">
            <label for="id_no_of_seats" class="form-label">No. of Seats</label>
            {{ form.no_of_seats }}
          </div>
          <div class="col-3">
            <label for="id_price" class="form-label">Price (per day)</label>
            {{ form.price }}
          </div>
          <div class="col-3">
            <label for="id_area" class="form-label">Area</label>
            {{ form.area }}
          </div>
          <div class="col-md-4">
            <label for="id_car_type" class="form-label">Car Type</label>
            {{ form.car_type }}
          </div>
          <div class="col-md-4">
            <label for="id_gear_type" class="form-label">Gear Type</label>
            {{ form.gear_type }}
          </div>
          <div class="col-md-4">
            <label for="id_fuel_type" class="form-label">Fuel Type</label>
            {{ form.fuel_type }}
          </div>
          <div class="col-md-8">
            <label for="id_description" class="form-label">Description</label>
            {{ form.description }}
          </div>
          <div class="col-md-4">
            <label for="id_image" class="form-label">Car Image</label>
            {{ form.image }}
          </div>
          <div class="col-12">
            <button type="submit" class="btn btn-success">{% if create %}Upload{% else %}Update{% endif %}</button>
            {% if not create %}<a class="btn btn-primary" href="{% url 'vendor_manage_vehicles' %}">Cancel</a>{% endif %}
          </div>
        </form>
    </div>
</section>

{% endblock content %}

templates/vehicle/list.html
{% extends "base.html" %} 

{% block title %}Available Vehicles{% endblock %} 

{% block content %} 

<section class="py-5 bg-dark">
    <div class="container px-5 my-5">
        <div class="text-center mb-5 text-white">
            <h1 class="fw-bolder">Available Vehicles</h1>
            <p class="lead fw-normal text-body-secondary mb-0">List of available cars for rental from any part of Nigeria.</p>
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5">
            {% for vehicle in vehicles %}
            {% include 'partials/_car_listings.html' %}
            {% empty %} No vehicle listing
            {% endfor %}
        </div>
        {% include 'partials/_pagination.html' with page_obj=vehicles %}
    </div>
</section>

{% endblock content %}

templates/vehicle/vendors.html
{% extends "base.html" %} 

{% block title %}Car Vendors{% endblock %} 

{% block content %} 

<section class="py-5 bg-dark">
    <div class="container px-5 my-5">
        <div class="text-center mb-5 text-white">
            <h1 class="fw-bolder">Car Vendors</h1>
            <p class="lead fw-normal text-body-secondary mb-0">Verified and Trusted Car Rental Firms From All Parts of Nigeria.</p>
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5">
            {% for vendor in vendors %}
            {% include 'partials/_vendor_listings.html' %}
            {% empty %} No vendor listing
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}