account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('logout/',
         auth_views.LogoutView.as_view(), name='logout'),
    path('login/',
         auth_views.LoginView.as_view(
             redirect_authenticated_user=True), name='login'),

    path('signup/customer/',
         views.CustomerSignUpView.as_view(), name='customer_signup'),
    path('customer/create-profile/',
         views.customer_create_profile, name='customer_create_profile'),
    path('customer/update-profile/',
         views.customer_update_profile, name='customer_update_profile'),
    path('customer/my-rentals/',
         views.customer_previous_rentals, name='customer_previous_rentals'),
    path('customer/verify/',
         views.customer_verification, name='customer_verification'),

    path('signup/carvendor/',
         views.VendorSignUpView.as_view(), name='vendor_signup'),
    path('vendor/create-profile/',
         views.vendor_create_profile, name='vendor_create_profile'),
    path('vendor/update-profile/',
         views.vendor_update_profile, name='vendor_update_profile'),
    path('vendor/my-vehicles/',
         views.vendor_manage_vehicles, name='vendor_manage_vehicles'),
     path('vendor/orders/',
         views.vendor_manage_orders, name='vendor_manage_orders'),
    path('vendor/<str:username>/',
         views.vendor_profile, name='vendor_profile'),
]

carrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('vehicles/', include('vehicle.urls', namespace='vehicle')),
    path('search/', search, name='search'),
    path('paystack/', include(('paystack.frameworks.django.urls', 'paystack'), namespace='paystack')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vehicle/urls.py
from django.urls import path

from . import views

app_name = 'vehicle'

urlpatterns = [
    path('create/', views.vehicle_create, name='create'),
    path('vendors/', views.vendor_list, name='vendors'),
    path('compare/', views.compare_vehicles, name='compare'),
    path('done/', views.payment_done, name='payment_done'),
    path('confirm-booking/',
         views.confirm_booking, name='confirm_booking'),
    path('add-to-compare/<int:pk>/',
         views.add_to_compare, name='add_to_compare'),
    path('<int:pk>/', views.vehicle_detail, name='detail'),
    path('<int:pk>/update/', views.vehicle_update, name='update'),
    path('<int:pk>/delete/', views.vehicle_delete, name='delete'),
    path('', views.vehicle_list, name='list'),

]

vehicle/models.py
from django.db import models
from django.conf import settings

from account.models import VendorProfile

User = settings.AUTH_USER_MODEL


class CarType(models.Model):
    name = models.CharField(max_length=20, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class GearType(models.Model):
    name = models.CharField(max_length=20, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class FuelType(models.Model):
    name = models.CharField(max_length=20, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Area(models.Model):
    city = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.city


class Vehicle(models.Model):
    vendor = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='vehicles')
    name = models.CharField(max_length=60)
    model = models.CharField(max_length=10, blank=True)
    color = models.CharField(max_length=20)
    no_of_seats = models.IntegerField()
    description = models.TextField(max_length=5000)
    car_type = models.ForeignKey(
        CarType, on_delete=models.PROTECT,
        blank=True, null=True)
    gear_type = models.ForeignKey(
        GearType, on_delete=models.PROTECT,
        blank=True, null=True)
    fuel_type = models.ForeignKey(
        FuelType, on_delete=models.PROTECT,
        blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='vehicle')
    is_available = models.BooleanField(default=True)
    license_plate = models.CharField(max_length=20, unique=True)
    area = models.ForeignKey(Area, on_delete=models.PROTECT)
    compares = models.ManyToManyField(
        User, related_name='compare', blank=True, default=None)
    # status: if car is available or not (out for rent)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.license_plate} : {self.name}"


class Rent(models.Model):
    PENDING = 'P'
    APPROVED = 'A'
    DECLINED = 'D'
    REQUEST_STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (DECLINED, 'Declined'),
    ]
    date_of_booking = models.DateField(blank=True, null=True)
    date_of_return = models.DateField(blank=True, null=True)
    advance_amount = models.IntegerField(blank=True, null=True) # remove
    total_amount = models.DecimalField(
        max_digits=12, decimal_places=2,
        blank=True, null=True)
    is_available = models.BooleanField(default=True)
    paid = models.BooleanField(default=False)
    request_status = models.CharField(
        max_length=1, choices=REQUEST_STATUS_CHOICES, default=PENDING) # remove
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='rents')
    vendor = models.ForeignKey(
        VendorProfile, on_delete=models.CASCADE, related_name='rents')
    paystack_id = models.CharField(max_length=150, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"Rent #{self.id}: {self.vehicle.name}"

    @property
    def total_days(self):
        date_of_booking = self.date_of_booking
        date_of_return = self.date_of_return
        if date_of_booking > date_of_return:
            return
        dates = (date_of_return - date_of_booking)
        return dates.days

    @property
    def get_cost(self):
        return self.vehicle.price

    @property
    def get_total_cost(self):
        return self.get_cost * self.total_days

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %} | RideOnHire</title>
    <link rel="stylesheet" href="{% static 'styles/fontawesome/all.min.css' %}">
    <link href="{% static 'styles/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand fw-bold" href="{% url 'home' %}"><i class="fa-solid fa-car-rear text-warning"></i> RideOnHire</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'vehicle:list' %}">Car Listings</a></li>
                    </ul>
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <a href="" class="btn btn-outline-light me-3 fw-bold"><i class="fa-solid fa-user me-1"></i> Log In</a>
                        <a href="" class="btn btn-warning text-white fw-bold"><i class="fa-solid fa-lock me-1"></i> Sign Up</a>
                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                {% if request.user.is_authenticated %}
                                {% if request.user.is_vendor %}
                                    <li><a class="dropdown-item" href="{% url 'vehicle:create' %}">Upload Vehicle</a></li>
                                    <li><a class="dropdown-item" href="{% url 'vendor_update_profile' %}">Update Profile</a></li>
                                    <li><a class="dropdown-item" href="{% url 'vendor_manage_vehicles' %}">Manage Vehicles</a></li>
                                    <li><a class="dropdown-item" href="{% url 'vendor_manage_orders' %}">Manage Order Rentals</a></li>
                                {% else %}
                                    <li><a class="dropdown-item" href="{% url 'customer_update_profile' %}">Update Profile</a></li>
                                    <li><a class="dropdown-item" href="{% url 'customer_previous_rentals' %}">Previous Rentals</a></li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                                {% else %}
                                <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                                {% endif %}
                            </ul>
                        </li> -->
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}{% endblock %}
    </main>
    <!-- Footer-->
    <footer class="bg-dark py-4 mt-auto">
        <div class="container">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0 text-white">&copy; {% now "Y" %} | RideOnHire</div></div>
                <div class="col-auto">
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="javascript:void()">Ogbonna Patrick Chijioke</a>
                    <span class="text-white mx-1">&middot;</span>
                </div>
            </div>
        </div>
    </footer>
    
    <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
    <script>
        window.onload = (event)=> {
         let myAlert = document.querySelector('.toast');
         let bsAlert = new bootstrap.Toast(myAlert);
         bsAlert.show();
        }
    </script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<header class="bg-dark py-5">
    <div class="container">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-7">
                <div class="my-5">
                    <span class="bg-white rounded-5 px-3 py-2"><i class="fa-solid fa-thumbs-up text-success"></i> 100% Trusted car rental platform in the World</span>
                    <h1 class="display-5 fw-bolder text-white mb-3 mt-4">
                        Find Your Best
                        <span class="text-warning d-block">Dream Car for Rental</span>
                    </h1>
                    <p class="lead fw-normal text-white-50 mb-4">We provide effective services for customers in need of vehicles to link up with car vendors who have cars available for rentals.</p>
                    <a class="btn btn-outline-warning px-3 py-2 me-sm-3" href="{% url 'vehicle:list' %}">View all Cars <i class="fa-solid fa-arrow-right ps-1"></i></a>
                </div>
            </div>
            <div class="col-lg-5">
                <img src="{% static 'car.svg' %}" class="w-100" alt="">
            </div>
        </div>
    </div>
</header>

<section class="bg-light py-lg-5">
    <div class="container my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Most Popular CarTypes</h2>
                    <p class="lead fw-normal text-body-secondary mb-5">Verified and Trusted Car Rental Firms</p>
                </div>
            </div>
        </div>
        <div class="row g-2 mb row-cols-1 row-cols-sm-2 row-cols-xl-4">
            <div class="">
                <div class="card border-0 h-100 py-3 px-2 shadow">
                    <div class="card-body text-center">
                        <span class="fa-stack fa-2x text-dark mb-3">
                            <i class="fa-solid fa-circle fa-stack-2x"></i>
                            <i class="fa-solid fa-caravan fa-stack-1x fa-inverse"></i>
                        </span>
                        <h5 class="mb-2 text-warning">Caravan</h5>
                        <span class="text-body-secondary">17 Cars</span>
                    </div>
                </div>
            </div>
            <div class="">
                <div class="card border-0 h-100 py-3 px-2 shadow">
                    <div class="card-body text-center">
                        <span class="fa-stack fa-2x text-dark mb-3">
                            <i class="fa-solid fa-circle fa-stack-2x"></i>
                            <i class="fa-solid fa-van-shuttle fa-stack-1x fa-inverse"></i>
                        </span>
                        <h5 class="mb-2 text-warning">Shuttle Van</h5>
                        <span class="text-body-secondary">17 Cars</span>
                    </div>
                </div>
            </div>
            <div class="">
                <div class="card border-0 h-100 py-3 px-2 shadow">
                    <div class="card-body text-center">
                        <span class="fa-stack fa-2x text-dark mb-3">
                            <i class="fa-solid fa-circle fa-stack-2x"></i>
                            <i class="fa-solid fa-truck fa-stack-1x fa-inverse"></i>
                        </span>
                        <h5 class="mb-2 text-warning">Truck</h5>
                        <span class="text-body-secondary">17 Cars</span>
                    </div>
                </div>
            </div>
            <div class="">
                <div class="card border-0 h-100 py-3 px-2 shadow">
                    <div class="card-body text-center">
                        <span class="fa-stack fa-2x text-dark mb-3">
                            <i class="fa-solid fa-circle fa-stack-2x"></i>
                            <i class="fa-solid fa-car-side fa-stack-1x fa-inverse"></i>
                        </span>
                        <h5 class="mb-2 text-warning">Sedan</h5>
                        <span class="text-body-secondary">17 Cars</span>
                    </div>
                </div>
            </div>
            <div class="">
                <div class="card border-0 h-100 py-3 px-2 shadow">
                    <div class="card-body text-center">
                        <span class="fa-stack fa-2x text-dark mb-3">
                            <i class="fa-solid fa-circle fa-stack-2x"></i>
                            <i class="fa-solid fa-bus-simple fa-stack-1x fa-inverse"></i>
                        </span>
                        <h5 class="mb-2 text-warning">Bus</h5>
                        <span class="text-body-secondary">17 Cars</span>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<section class="bg-white py-lg-5">
    <div class="container my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder text-warning-emphasis">Explore Featured Cars</h2>
                    <p class="lead fw-normal text-body-secondary mb-5">Available cars for rental that you can choose from</p>
                </div>
            </div>
        </div>
        <div class="row gx-5">
            {% for vehicle in vehicles %}
            {% include 'partials/_car_listings.html' %}
            {% empty %} No vehicle listing
            {% endfor %}
        </div>
    </div>
</section>

<section class="text-bg-dark py-lg-5">
    <div class="container my-5">

    </div>
</section>

{% endblock %}

templates/search.html
{% extends "base.html" %} 

{% block title %}Search Results{% endblock %} 

{% block content %} 

<section class="py-5 bg-dark">
    <div class="container px-5 my-5">
        <div class="text-center mb-5 text-white">
            <h1 class="fw-bolder mb-3">Search Results</h1>
            <form action="{% url 'search' %}" method="get">
                <div class="row">
                    <div class="col-lg-4 form-group mb-3">
                        <input class="form-control form-control-lg" id="name" type="text" placeholder="Enter car name" name="car_name" value="{{ request.GET.car_name }}" />
                    </div>
                    <div class="col-lg-4 form-group mb-3">
                        <input class="form-control form-control-lg" id="min_price" type="number" placeholder="Enter min price" name="min_price" value="{{ request.GET.min_price }}" />
                    </div>
                    <div class="col-lg-4 form-group mb-3">
                        <input class="form-control form-control-lg" id="max_price" type="number" placeholder="Enter max price" name="max_price" value="{{ request.GET.max_price }}" />
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-3 form-group mb-3">
                        <select name="gear_type" class="form-select form-control-lg" id="id_gear_type" value="{{ request.GET.gear_type }}">
                            <option value="" selected>--Gear Type--</option>
                            {% for gear_type in gear_types %}
                            <option value="{{ gear_type.pk }}">{{ gear_type.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-lg-3 form-group mb-3">
                        <select name="car_type" class="form-select form-control-lg" id="id_car_type">
                            <option value="" selected>--Car Type--</option>
                            {% for car_type in car_types %}
                            <option value="{{ car_type.pk }}">{{ car_type.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-lg-3 form-group mb-3">
                        <select name="fuel_type" class="form-select form-control-lg" id="id_fuel_type">
                            <option value="" selected>--Fuel Type--</option>
                            {% for fuel_type in fuel_types %}
                            <option value="{{ fuel_type.pk }}">{{ fuel_type.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-lg-3 form-group mb-3">
                        <select name="area" class="form-select form-control-lg" id="id_area">
                            <option value="" selected>--Area--</option>
                            {% for area in areas %}
                            <option value="{{ area.pk }}">{{ area.city }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </form>
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5">
            {% for vehicle in vehicles %}
            {% include 'partials/_car_listings.html' %}
            {% empty %} No vehicle listing
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}